ghOSt OSS: Temporarily freeze bazel version to 5.4.0
Recently `bazel` deprecated `@bazel_tools//platforms` and it is causing
`bazel build` to fail with the following error:

```
bazel_tools/platforms/BUILD:89:6: in alias rule
@bazel_tools//platforms:windows: Constraints from @bazel_tools//platforms have
been removed. Please use constraints from @platforms repository embedded in
Bazel, or preferably declare dependency on
https://github.com/bazelbuild/platforms. See
https://github.com/bazelbuild/bazel/issues/8622 for details.
```

The error is coming from ghOSt's external dependencies and we identified two
locations where `bazel build` uses deprecated `@bazel_tools//platforms`:
`com_google_googletest` and `tbb`.

For `com_google_googletest`, this change bumps up the bazel dependency version
to `release-1.12.1` (Jun 27 2022) that has already addressed this issue.
However, for `tbb`, the issue has not been addressed. For a temporary solution,
we freeze the bazel version to be 5.4.0. Once all the dependencies migrate out
of the deprecated `@bazel_tools//platforms`, we can start supporting bazel
version 6.

Users may see the following error message and can resolve the issue by
installing `bazel-5.4.0` as noted below.

```
ERROR: The project you're trying to build requires Bazel 5.4.0 (specified in
/a/b/c/.bazelversion), but it wasn't found in /usr/bin.

You can install the required Bazel version via apt:
  sudo apt update && sudo apt install bazel-5.4.0

  If this doesn't work, check Bazel's installation instructions for help:
    https://bazel.build/install/ubuntu
```